apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-demo-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RajkumarR1206/-gitops-argocd-demo.git
    targetRevision: HEAD
    path: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
